{
  "code": 0,
  "is_server_open": true,
  "is_firewall_open": false,
  "cdn_url": "https://dl.cdn.freefiremobile.com/advance/ABHotUpdates/",
  "abhotupdate_cdn_url": "https://dl.cdn.freefiremobile.com/advance/ABHotUpdates/",
  "backup_cdn_url": "https://dl.cdn.freefiremobile.com/advance/ABHotUpdates/",
  "img_cdn_url": "https://dl.cdn.freefiremobile.com/common/",
  "login_download_optionalpack": "optionalclothres:shaders|optionalpetres:optionalpetres_commonab_shader|optionallobbyres:",
  "need_track_hotupdate": false,
  "abhotupdate_check": "",
  "latest_release_version": "OB53",
  "min_hint_size": 12,
  "space_required_in_GB": 0,
  "should_check_ab_load": false,
  "force_refresh_restype": "",
  "remote_version": "68.53.1",
  "server_url": "https://login.advance.freefiremobile.com/",
  "is_review_server": false,
  "use_login_optional_download": true,
  "use_background_download": false,
  "use_background_download_lobby": false,
  "country_code": "MA",
  "client_ip": "160.164.250.102",
  "gdpr_version": 0,
  "billboard_cdn_url": "https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/idfU35btFB7nn9Vy01M.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/idfU35btFB7nn9Vy02M.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/idfU35btFB7nn9Vy03M.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/idfU35btFB7nn9Vy04.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/idfU35btFB7nn9Vy05.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/idfU35btFB7nn9Vy06.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/idfU35btFB7nn9Vy07.ff_extend",
  "billboard_msg": "",
  "web_url": "",
  "billboard_bg_url": "https://dl.cdn.freefiremobile.com/common/OB23/version/Patch_Bg.png",
  "max_store": "",
  "max_web": "",
  "max_video": "",
  "patchnote_url": "https://dl.dir.freefiremobile.com/common/web_event/aswqooiwd/ihYhRVZU.html?lang=ind",
  "multi_region": "",
  "need_check_ip_list": [
    "103.247.205.162"
  ],
  "network_log_server": "http://103.247.205.162:39006/",
  "web_log_server": null,
  "login_failed_count": 2,
  "test_url": "",
  "core_url": "csoversea.castle.freefiremobile.com",
  "core_ip_list": [
    "0.0.0.0",
    "50.109.27.134",
    "129.226.2.163",
    "129.226.1.13",
    "129.226.1.16"
  ],
  "appstore_url": "https://ff-advance.ff.garena.com/",
  "backup_appstore_url": null,
  "garena_login": false,
  "garena_hint": false,
  "gop_url": "",
  "gamevar": "var_name,comment,var_type,var_value,var_region,var_platform\nFastQuit_NativeDoneFast,FastQuit_NativeDoneFast,bool,true,,\n",
  "remote_option_version": "optionallocres:90|optionalavatarres:202|optionalclothres:0|optionalfootballres:0|optionalfullscreencgres:0|optionalhuntinggroundres:0|optionalinfection:0|optionalingameres:150|optionallobbyres:0|optionallonewolfres:85|optionallonewolfstrikeoutres:0|optionalludores:0|optionalmap1res:256|optionalmap2res:96|optionalmap4res:87|optionalmaphippores:77|optionalmapmaxres:0|optionalmapponyres:46|optionalmapres:295|optionalnewblast:0|optionalpetres:0|optionalrushb:0|optionalrushingpetsres:0|optionalsingersbres:0|optionalsnowduelres:0|optionalsocialres:70|optionaltrainingres:108|optionalugcoldparadiseres:12|optionalugcres:252|optionalvoiceres:0|optionalwerewolves:0|optionalwerunres:38",
  "remote_option_version_astc": "optionallocres:90",
  "device_whitelist_version": "1.5.0",
  "whitelist_mask": 1150,
  "whitelist_info": "3,4,1,2,1,1980,3",
  "device_whitelist_sp_version": "1.0.0",
  "whitelist_sp_mask": 0,
  "ggp_url": "adv.gin.freefiremobile.com"
}
