{
  "code": 0,
  "is_server_open": true,
  "is_firewall_open": false,
  "cdn_url": "https://dl.cdn.freefiremobile.com/live/ABHotUpdates/",
  "backup_cdn_url": "https://dl.cdn.freefiremobile.com/live/ABHotUpdates/",
  "abhotupdate_cdn_url": "https://dl-core.cdn.freefiremobile.com/live/ABHotUpdates/",
  "img_cdn_url": "https://dl.cdn.freefiremobile.com/common/",
  "login_download_optionalpack": "optionalclothres:shaders|optionalpetres:optionalpetres_commonab_shader|optionallobbyres:",
  "need_track_hotupdate": true,
  "abhotupdate_check": "cache_res;assetindexer;SH-Gpp",
  "latest_release_version": "",
  "min_hint_size": 1,
  "space_required_in_GB": 1.48,
  "should_check_ab_load": false,
  "force_refresh_restype": "optionalavatarres",
  "remote_version": "1.108.1",
  "server_url": "http://192.168.8.122:5000/",
  "is_review_server": false,
  "use_login_optional_download": true,
  "use_background_download": false,
  "use_background_download_lobby": false,
  "country_code": "MA",
  "client_ip": "160.164.250.102",
  "gdpr_version": 0,
  "billboard_cdn_url": "https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/sgfU35btFB7nn9Vy01.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/sgfU35btFB7nn9Vy02.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/sgfU35btFB7nn9Vy03.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/sgfU35btFB7nn9Vy04.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/sgfU35btFB7nn9Vy05.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/sgfU35btFB7nn9Vy06.ff_extend;https://dl.dir.freefiremobile.com/common/OB52/CSH/patchupdate/sgfU35btFB7nn9Vy07.ff_extend",
  "billboard_msg": "",
  "web_url": "",
  "billboard_bg_url": "https://dl.cdn.freefiremobile.com/common/OB23/version/Patch_Bg.png",
  "max_store": "",
  "max_web": "",
  "max_video": "",
  "patchnote_url": "https://dl.dir.freefiremobile.com/common/web_event/aswqooiwd/EUlwfWCv.html?lang=en",
  "multi_region": "",
  "need_check_ip_list": [],
  "network_log_server": "https://sgnetwork.ggblueshark.com/",
  "web_log_server": "https://networkselftest.ff.garena.com/api/",
  "login_failed_count": 2,
  "test_url": "",
  "core_url": "csoversea.castle.freefiremobile.com",
  "core_ip_list": [
    "0.0.0.0",
    "50.109.27.134",
    "129.226.2.163",
    "129.226.1.13",
    "129.226.1.16"
  ],
  "appstore_url": "http://play.google.com/store/apps/details?id=com.dts.freefireth",
  "backup_appstore_url": "",
  "garena_login": false,
  "garena_hint": false,
  "gop_url": "",
  "gamevar": "var_name,comment,var_type,var_value\nvar_name,comment,\"var_type float, int, bool\",var_value\nANODisabledRegions,关闭MTP的地区,string,\"IND,NA\"\nANODisabledClientVariant,ANODisabledClientVariant,string,\"ClientUsingVersion_MAX_HPE,ClientUsingVersion_FFI,ClientUsingVersion_MAX|IND,ClientUsingVersion_MAX|NA,ClientUsingVersion_NORMAL|NA\"\nEnableMtpLiteDataRegion,mtp轻特征开关,string,\"BR,EUROPE,ID,ME,US,RU,SAC,SG,TH,TW,VN,PK,ZA,BD\"\nANOEmulatorCheckDisbaledClientVariant,ANOEmulatorCheckDisbaledClientVariant,string,\"ClientUsingVersion_FFI,ClientUsingVersion_MAX,ClientUsingVersion_NORMAL\"\nForceTutorial_ChangeHudABTest,fps流程中打开hud选择界面的概率,float,-1\n",
  "remote_option_version": "optionallocres:48|optionalavatarres:723|optionalclothres:1144|optionalfootballres:27|optionalfullscreencgres:314|optionalhuntinggroundres:246|optionalinfection:125|optionalingameres:469|optionallobbyres:577|optionallonewolfres:86|optionallonewolfstrikeoutres:59|optionalludores:42|optionalmap1res:385|optionalmap2res:156|optionalmap4res:139|optionalmaphippores:115|optionalmapres:357|optionalnewblast:163|optionalpetres:871|optionalrushb:108|optionalrushingpetsres:84|optionalsnowduelres:35|optionalsocialres:223|optionaltrainingres:297|optionalugcres:781|optionalvoiceres:338|optionalwerewolves:153|optionalwerunres:92|optionalmapponyres:204|optionalugcoldparadiseres:34|optionalmultiregionres:29",
  "remote_option_version_astc": "optionallocres:48|optionalavatarres:685|optionalclothres:1144|optionalfootballres:29|optionalfullscreencgres:301|optionalhuntinggroundres:216|optionalinfection:124|optionalingameres:427|optionallobbyres:576|optionallonewolfres:206|optionallonewolfstrikeoutres:155|optionalludores:175|optionalmap1res:385|optionalmap2res:192|optionalmap4res:175|optionalmaphippores:115|optionalmapres:391|optionalnewblast:162|optionalpetres:871|optionalrushb:241|optionalrushingpetsres:217|optionalsnowduelres:35|optionalsocialres:215|optionaltrainingres:267|optionalugcres:725|optionalvoiceres:373|optionalwerewolves:286|optionalwerunres:81|optionalmapponyres:204|optionalugcoldparadiseres:33|optionalmultiregionres:27",
  "device_whitelist_version": "1.4.0",
  "whitelist_mask": 0,
  "device_whitelist_sp_version": "1.0.0",
  "whitelist_sp_mask": 0,
  "ggp_url": "gin.freefiremobile.com"
}
