{
  "code": 0,
  "is_server_open": true,
  "is_firewall_open": false,
  "cdn_url": "https://dl.bs.freefiremobile.com/live/ABHotUpdates/",
  "backup_cdn_url": "https://dl.bs.freefiremobile.com/live/ABHotUpdates/",
  "abhotupdate_cdn_url": "https://core-bs.freefiremobile.com/live/ABHotUpdates/",
  "img_cdn_url": "https://dl.bs.freefiremobile.com/common/",
  "login_download_optionalpack": "optionalclothres:shaders|optionalpetres:optionalpetres_commonab_shader|optionallobbyres:",
  "need_track_hotupdate": true,
  "abhotupdate_check": "cache_res;assetindexer;SH-Gpp",
  "latest_release_version": "OB53",
  "min_hint_size": 1,
  "space_required_in_GB": 1.48,
  "should_check_ab_load": false,
  "force_refresh_restype": "optionalavatarres",
  "remote_version": "1.123.17",
  "server_url": "https://loginbp.ggpolarbear.com/",
  "is_review_server": false,
  "use_login_optional_download": true,
  "use_background_download": true,
  "use_background_download_lobby": true,
  "country_code": "BR",
  "client_ip": "105.129.222.82",
  "gdpr_version": 0,
  "billboard_cdn_url": "https://dl.dir.freefiremobile.com/common/OB53/CSH/patchupdate/meenhfuHFHf101.ff_extend;https://dl.dir.freefiremobile.com/common/OB53/CSH/patchupdate/meenhfuHFHf102.ff_extend;https://dl.dir.freefiremobile.com/common/OB53/CSH/patchupdate/meenhfuHFHf103.ff_extend;https://dl.dir.freefiremobile.com/common/OB53/CSH/patchupdate/meenhfuHFHf104.ff_extend;https://dl.dir.freefiremobile.com/common/OB53/CSH/patchupdate/meenhfuHFHf105.ff_extend;https://dl.dir.freefiremobile.com/common/OB53/CSH/patchupdate/meenhfuHFHf106.ff_extend;https://dl.dir.freefiremobile.com/common/OB53/CSH/patchupdate/meenhfuHFHf107.ff_extend",
  "billboard_msg": "",
  "web_url": "",
  "billboard_bg_url": "https://dl.cdn.freefiremobile.com/common/OB23/version/Patch_Bg.png",
  "max_store": "",
  "max_web": "",
  "max_video": "",
  "patchnote_url": "https://dl.dir.freefiremobile.com/common/web_event/aswqooiwd/8vdjQOul.html?lang=en",
  "multi_region": "BR",
  "need_check_ip_list": [
    "202.81.108.9"
  ],
  "network_log_server": "https://menetwork.ggblueshark.com/",
  "web_log_server": "https://networkselftest.ff.garena.com/api/",
  "login_failed_count": 2,
  "test_url": "",
  "core_url": "csoversea.castle.freefiremobile.com",
  "core_ip_list": [
    "0.0.0.0",
    "50.109.27.134",
    "129.226.2.163",
    "129.226.1.13",
    "129.226.1.16"
  ],
  "appstore_url": "http://play.google.com/store/apps/details?id=com.dts.freefireth",
  "backup_appstore_url": "",
  "garena_login": false,
  "garena_hint": false,
  "gop_url": "",
  "gamevar": "var_name,comment,var_type,var_value,var_region,var_platform\nvar_name,comment,var_type,var_value,var_region,var_platform\nReleaseMemForMatchEndFor3I3A,ReleaseMemForMatchEndFor3I3A,bool,false,,\nEnableReportIOFailedLogs,EnableReportIOFailedLogs,bool,false,,\nEnableFFOPortingHDAnimation,EnableFFOPortingHDAnimation,bool,false,,\nAutoEnemyMarkSwitch,AutoEnemyMarkSwitch,int,2,,\nIsUseMedkitForceStand,IsUseMedkitForceStand,bool,false,,\nPGSRecallReadIPRegions_Mobile,PGSRecallReadIPRegions_Mobile,string,,,\nPGSRecallReadIPRegions_HPE,PGSRecallReadIPRegions_HPE,string,,,\nPGSRecallWriteIPRegions_Mobile,PGSRecallWriteIPRegions_Mobile,string,,,\nPGSRecallWriteIPRegions_HPE,PGSRecallWriteIPRegions_HPE,string,,,\nEnableFileInfoEncryptionIOS,EnableFileInfoEncryptionIOS,bool,TRUE,SG,\nEnableFileInfoEncryptionAndroid,EnableFileInfoEncryptionAndroid,bool,TRUE,SG,\n",
  "remote_option_version": "optionallocres:49|optionalavatarres:757|optionalclothres:1184|optionalfootballres:27|optionalfullscreencgres:319|optionalhuntinggroundres:246|optionalinfection:125|optionalingameres:503|optionallobbyres:613|optionallonewolfres:86|optionallonewolfstrikeoutres:59|optionalludores:42|optionalmap1res:385|optionalmap2res:156|optionalmap4res:139|optionalmaphippores:115|optionalmapres:357|optionalnewblast:163|optionalpetres:871|optionalrushb:108|optionalrushingpetsres:84|optionalsnowduelres:65|optionalsocialres:223|optionaltrainingres:297|optionalugcres:809|optionalvoiceres:341|optionalwerewolves:153|optionalwerunres:92|optionalmapponyres:204|optionalugcoldparadiseres:34|optionalmultiregionres:29",
  "remote_option_version_astc": "optionallocres:49|optionalavatarres:719|optionalclothres:1184|optionalfootballres:29|optionalfullscreencgres:306|optionalhuntinggroundres:216|optionalinfection:124|optionalingameres:461|optionallobbyres:612|optionallonewolfres:206|optionallonewolfstrikeoutres:155|optionalludores:175|optionalmap1res:385|optionalmap2res:192|optionalmap4res:175|optionalmaphippores:115|optionalmapres:391|optionalnewblast:162|optionalpetres:871|optionalrushb:241|optionalrushingpetsres:217|optionalsnowduelres:65|optionalsocialres:215|optionaltrainingres:267|optionalugcres:751|optionalvoiceres:376|optionalwerewolves:286|optionalwerunres:81|optionalmapponyres:204|optionalugcoldparadiseres:33|optionalmultiregionres:27",
  "ggp_url": "gin.freefiremobile.com"
}
